version: "3.1"

services:
  db:
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./data:/docker-entrypoint-initdb.d  # ./data ディレクトリにある init.sql スクリプトを使用して、MySQLサーバーが初めて起動したときにデータベースとテーブルが作成され、初期データが挿入される
    ports:
      - "3306:3306"
